### ISSUE TITLE
Can't switch custom maps.

### ISSUE THREAD

**Issue by sunencheng** [Chris7c0/ACS#1]
"!admin" command can change custom maps ,but acs_map_list.txt has no custom maps,"!votemaps" neither.

**Comment by Chris7c0** [comment]
Hello @sunencheng,

This version of ACS only automatically works for the standard L4D2 maps.  However, it does support custom maps, you just need to modify the ACS Map List file to include them.  After running the plugin at least once on your server, this file can be found here:

`.../l4d2serverfolder/left4dead2/addons/sourcemod/configs/acs_map_list.txt`

Alternatively, you can find a forked version of ACS that does support automatic custom maps importing here:

https://forums.alliedmods.net/showthread.php?t=308708
